config/routes.rb
Rails.application.routes.draw do
  resources :clients do
  	member do
  		get :change_stage
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/1
  def show
  end

  def change_stage
    @client = Client.find(params[:id])
    @client.state += 1
    @client.first_contact = Date.today
    if @client.save
      redirect_to action: "index"
    end
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:name, :email, :address, :phone, :detail, :state, :reserve, :birthday, :first_contact)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="content-wrapper" style="min-height: 1036.3px;">
  <%= form_for(client) do |f| %>
    <% if client.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

        <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>

    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>

    <div class="field">
      <%= f.label :detail %>
      <%= f.text_area :detail %>
    </div>

    <div class="field">
      <%= f.label :state %>
      <%= f.number_field :state %>
    </div>

    <div class="field">
      <%= f.label :reserve %>
      <%= f.date_select :reserve %>
    </div>

    <div class="field">
      <%= f.label :birthday %>
      <%= f.date_select :birthday %>
    </div>

    <div class="field">
      <%= f.label :first_contact %>
      <%= f.date_select :first_contact %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<!--     CRM Division    -->
<%
  n_cols = 5
  stage_names = ['1º Estágio','2º Estágio','3º Estágio','4º Estágio','5º Estágio','Todos Clientes']
%>

<div class="content-wrapper" style="min-height: 1036.3px;">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>CRM</h1>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <p id="notice"><%= notice %></p>
        </div>
          
        <div class="col-sm-12 col-md-12">
          <% for i in 0..n_cols - 1 %>
            <!-- Count Stages -->
            <% clientes_no_estagio = 0
            @clients.each do |client|
              if client.state == i
                clientes_no_estagio += 1
              end
            end
            %>

            <div class="col-sm-12 col-md-2">
              <!--Print Stage Name-->
              <h2><%= stage_names[i] =%></h2>
              <p>(<%= clientes_no_estagio =%> Clientes)</p>
              <hr>
              
              <!-- Print Clients on each stage -->
              <% @clients.each do |client| %>
                <% if client.state == i %>
                  <div class="box box-solid">
                    <div class="box-body">
                      <div class="clientColor">
                        <% if (Date.today - client.first_contact).to_i  > 0 %>
                          <div style="background-color: white">
                            <!--Style cliente on CRM here-->
                            <%= link_to client.name, client %><br>
                            <%= link_to 'go ahead', change_stage_client_path(client), :class => ""%>
                          </div>
                        <% else %>
                            <div style="background-color: white">
                            <!--Style cliente on CRM here-->
                            <%= link_to client.name, client %><br>
                            <%= link_to 'go ahead', change_stage_client_path(client), :class => ""%>
                          </div>
                        <%end%>
                      </div>
                    </div>
                  </div>                  
                <% end %>
              <% end %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<div class="content-wrapper" style="min-height: 1036.3px;">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @client.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @client.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @client.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @client.phone %>
  </p>

  <p>
    <strong>Detail:</strong>
    <%= @client.detail %>
  </p>

  <p>
    <strong>State:</strong>
    <%= @client.state %>
  </p>

  <p>
    <strong>Reserve:</strong>
    <%= @client.reserve %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= @client.birthday %>
  </p>

  <p>
    <strong>First contact:</strong>
    <%= @client.first_contact %>
  </p>

  <%= link_to 'Edit', edit_client_path(@client) %> |
  <%= link_to 'Back', clients_path %> |
  <%= link_to 'Destroy', client_path(@client), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P03</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Tell the browser to be responsive to screen width -->
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<!-- Bootstrap 3.3.6 -->
	<%= stylesheet_link_tag "bootstrap.min.css" %>
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- Theme style -->
	<%= stylesheet_link_tag "AdminLTE.min.css" %>
	<%= stylesheet_link_tag "skin-blue.min.css" %>

  </head>

	<body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
	<!--Header-->
	
		<header class="main-header">
			<%= link_to 'Cuco Maluco', root_path, :class =>"logo"%>
		<!-- Header Navbar: style can be found in header.less -->
		<nav class="navbar navbar-static-top" role="navigation">
		  <!-- Sidebar toggle button -->
		  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
	        <span class="sr-only">Toggle navigation</span>
	      </a>
		  <!-- Navbar Right Menu -->
		  <div class="navbar-custom-menu">
		    <ul class="nav navbar-nav">

		      <!-- Messages: style can be found in dropdown.less-->
		      <li class="dropdown messages-menu">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		          <i class="fa fa-envelope-o"></i>
		          <span class="label label-success">4</span>
		        </a>
		        <ul class="dropdown-menu">
		          <li class="header">You have 4 messages</li>
		          <li>
		            <!-- inner menu: contains the actual data -->
		            <ul class="menu">
		              <li><!-- start message -->
		                <a href="#">
		                  <div class="pull-left">
		                    <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
		                  </div>
		                  <h4>
		                    Sender Name
		                    <small><i class="fa fa-clock-o"></i> 5 mins</small>
		                  </h4>
		                  <p>Message Excerpt</p>
		                </a>
		              </li><!-- end message -->
		              ...
		            </ul>
		          </li>
		          <li class="footer"><a href="#">See All Messages</a></li>
		        </ul>
		      </li>

		      <!-- Notifications: style can be found in dropdown.less -->
		      <li class="dropdown notifications-menu">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		          <i class="fa fa-bell-o"></i>
		          <span class="label label-warning">10</span>
		        </a>
		        <ul class="dropdown-menu">
		          <li class="header">You have 10 notifications</li>
		          <li>
		            <!-- inner menu: contains the actual data -->
		            <ul class="menu">
		              <li>
		                <a href="#">
		                  <i class="ion ion-ios-people info"></i> Notification title
		                </a>
		              </li>
		              ...
		            </ul>
		          </li>
		          <li class="footer"><a href="#">View all</a></li>
		        </ul>
		      </li>

		      <!-- Tasks: style can be found in dropdown.less -->
		      <li class="dropdown tasks-menu">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		          <i class="fa fa-flag-o"></i>
		          <span class="label label-danger">9</span>
		        </a>
		        <ul class="dropdown-menu">
		          <li class="header">You have 9 tasks</li>
		          <li>
		            <!-- inner menu: contains the actual data -->
		            <ul class="menu">
		              <li><!-- Task item -->
		                <a href="#">
		                  <h3>
		                    Design some buttons
		                    <small class="pull-right">20%</small>
		                  </h3>
		                  <div class="progress xs">
		                    <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
		                      <span class="sr-only">20% Complete</span>
		                    </div>
		                  </div>
		                </a>
		              </li><!-- end task item -->
		              ...
		            </ul>
		          </li>
		          <li class="footer">
		            <a href="#">View all tasks</a>
		          </li>
		        </ul>
		      </li>

		      <!-- User Account: style can be found in dropdown.less -->
		      <li class="dropdown user user-menu">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		          <span class="hidden-xs">Usuário 1</span>
		        </a>
		        <ul class="dropdown-menu">
		          <!-- Menu Footer-->
		          <li class="user-footer">
		          	<a href="#" class="btn btn-default btn-flat">Sign out</a>
		          </li>
		        </ul>
		      </li>
		    </ul>
		  </div>
		</nav>
		</header>


		<!-- SIDE BAR -->
		<aside class="main-sidebar">
		  <!-- Sidebar user panel -->
		  <!-- <div class="user-panel">
		    <div class="pull-left info">
		      <p>Alexander Pierce</p>
		      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
		    </div>
		  </div> -->
		  <!-- search form -->
		  <form action="#" method="get" class="sidebar-form">
		    <div class="input-group">
		      <input name="q" class="form-control" placeholder="Search..." type="text">
		    <span class="input-group-btn">
		    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
		    </button>
		    </span>
		    </div>
		  </form>
		  <!-- /.search form -->
		  <!-- sidebar menu: : style can be found in sidebar.less -->
		  <ul class="sidebar-menu tree" data-widget="tree">
		    <li class="header">MENU DE NAVEGAÇÃO</li>
		    <td>
		      <button type="button" class="btn btn-block btn-primary btn-sm">
		        <%= link_to 'Adicionar Cliente', new_client_path, {:style=>'color:#FFFFFF;'}%>
		      </button>
		      
		    </td>
		    <li>
		      <a href="#">
		        <i class="fa fa-th"></i> 
		        <span>LOGIN</span>
		        <span class="pull-right-container">
		          <i class="fa fa-angle-left pull-right"></i>
		        </span>
		      </a>
		    </li>
		    <li class="treeview">
		      <a href="#">
		        <i class="fa fa-tags"></i> 
		        <span>CRM</span>
		        <span class="pull-right-container">
		          <i class="fa fa-angle-left pull-right"></i>
		        </span>
		      </a>
		    </li>
		    <li class="treeview">
		      <a href="#">
		        <i class="fa fa-laptop"></i>
		        <span>NOTIFICAÇÕES</span>
		        <span class="pull-right-container">
		          <i class="fa fa-angle-left pull-right"></i>
		        </span>
		      </a>
		    </li>
		    <li class="treeview">
		      <a href="#">
		        <i class="fa fa-calendar"></i>
		        <span>CALENDARIO</span>
		        <span class="pull-right-container">
		          <i class="fa fa-angle-left pull-right"></i>
		        </span>
		      </a>
		    </li>
		    <li class="treeview">
		      <a href="#">
		        <i class="fa fa-book"></i>
		        <span>CLIENTES CADASTRADOS</span>
		        <span class="pull-right-container">
		          <i class="fa fa-angle-left pull-right"></i>
		        </span>
		      </a>
		    </li>
		    <li class="treeview">
		      <a href="#">
		        <i class="fa fa-money"></i>
		        <span>FLUXO DE CAIXA</span>
		        <span class="pull-right-container">
		          <i class="fa fa-angle-left pull-right"></i>
		        </span>
		      </a>
		    </li>
		    
		    <li class="header">LABELS</li>
		    <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
		    <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
		    <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
		  </ul>
		</aside>


    	<%= yield %>
	</body>
</html>

app/views/welcome/index.html.erb
<style>
  @media(min-width: 768px){
    .container_1{
      display: flex;
      justify-content: space-around;
    }
  }

  .container_1 div{
    border: 1px #ccc solid;
    padding: 10px;
  }

  .box_1{
    flex-basis: 32%;
  }
</style>



<div class="content-wrapper" style="min-height: 1036.3px;">
  <br>
  <div class="container_1">
    <div class="box_1">
      <h3>Client 1</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>  
    </div>
    <div class="box_1">
      <h3>Client 2</h3>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>  
    </div>
    <div class="box_1">
      <h3>Client 3</h3>
      <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>  
    </div>
  </div>
  <br>
  <div class="container_1">
    <div class="box_1">
      <h3>Client 4</h3>
      <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>  
    </div>
    <div class="box_1">
      <h3>Client 5</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo</p>  
    </div>
    <div class="box_1">
      <h3>Client 6</h3>
      <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam</p>  
    </div>
  </div>
</div>